# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/timing.xdc

# Block Designs: bd/ALU/ALU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU || ORIG_REF_NAME==ALU} -quiet] -quiet

# IP: bd/ALU/ip/ALU_c_addsub_0_0/ALU_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_c_addsub_0_0 || ORIG_REF_NAME==ALU_c_addsub_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_c_addsub_1_0/ALU_c_addsub_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_c_addsub_1_0 || ORIG_REF_NAME==ALU_c_addsub_1_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_mult_gen_0_0/ALU_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_mult_gen_0_0 || ORIG_REF_NAME==ALU_mult_gen_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_and16_0_0/ALU_and16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_and16_0_0 || ORIG_REF_NAME==ALU_and16_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_or16_0_0/ALU_or16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_or16_0_0 || ORIG_REF_NAME==ALU_or16_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xor16_0_0/ALU_xor16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xor16_0_0 || ORIG_REF_NAME==ALU_xor16_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_div_gen_0_2/ALU_div_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_div_gen_0_2 || ORIG_REF_NAME==ALU_div_gen_0_2} -quiet] -quiet

# IP: bd/ALU/ip/ALU_mod16_0_0/ALU_mod16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_mod16_0_0 || ORIG_REF_NAME==ALU_mod16_0_0} -quiet] -quiet

# XDC: bd/ALU/ALU_ooc.xdc
