%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\josh9.DESKTOP-HLQ5OEN\Documents\CMPE314\lab3\Square Graph1.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/10/11 02:47:07

%% Initialize variables.
filename = 'C:\Users\josh9.DESKTOP-HLQ5OEN\Documents\CMPE314\lab3\Square Graph1.txt';
delimiter = '\t';
startRow = 5;

%% Format string for each line of text:
%   column1: text (%q)
%	column2: double (%f)
%   column3: text (%q)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%f%q%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
time2 = dataArray{:, 1};
Ch1 = dataArray{:, 2};
time3 = dataArray{:, 3};
Gen1 = dataArray{:, 4};
plot (time2,Ch1,time3,Gen1);


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;