# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param project.singleFileAddWarning.threshold 0
set_param chipscope.maxJobs 3
set_param chipscope.flow 0
set_param synth.enableIncremental 0
set_param xicom.use_bs_reader 1
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.cache/wt} [current_project]
set_property parent.project_path {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/ip_repo}
  c:/Users/nehmy/AppData/Roaming/Xilinx/ip_repo
} [current_project]
update_ip_catalog
set_property ip_output_repo {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/{C:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.cache/ip}} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet {{c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_cc_early.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_cc_late.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_gc_late.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top dbg_hub -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all dbg_hub_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dbg_hub.dcp
create_report "dbg_hub_synth_1_synth_report_utilization_0" "report_utilization -file dbg_hub_utilization_synth.rpt -pb dbg_hub_utilization_synth.pb"

if { [catch {
  file copy -force {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.runs/dbg_hub_synth_1/dbg_hub.dcp} {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.dcp}
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.ip_user_files/ip/dbg_hub}]} {
  catch { 
    file copy -force {{c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_stub.v}} {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.ip_user_files/ip/dbg_hub}
  }
}

if {[file isdir {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.ip_user_files/ip/dbg_hub}]} {
  catch { 
    file copy -force {{c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_stub.vhdl}} {c:/Users/nehmy/OneDrive/Desktop/415 Hws and Projects/HW4Phase1 - 1/HW4Phase1/HW4/HW4.runs/impl_1/.Xil/Vivado-6092-DESKTOP-KFAJ11H/dc_drv.0/dc/prj_ip.ip_user_files/ip/dbg_hub}
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
