set_property SRC_FILE_INFO {cfile:c:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/sources_1/bd/ALU/ip/ALU_c_addsub_0_0/ALU_c_addsub_0_0/ALU_c_addsub_0_0_in_context.xdc rfile:../../../../../HW4.srcs/sources_1/bd/ALU/ip/ALU_c_addsub_0_0/ALU_c_addsub_0_0/ALU_c_addsub_0_0_in_context.xdc id:1 order:EARLY scoped_inst:mux/ALU_intan/c_addsub_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/sources_1/bd/ALU/ip/ALU_c_addsub_1_0/ALU_c_addsub_1_0/ALU_c_addsub_1_0_in_context.xdc rfile:../../../../../HW4.srcs/sources_1/bd/ALU/ip/ALU_c_addsub_1_0/ALU_c_addsub_1_0/ALU_c_addsub_1_0_in_context.xdc id:2 order:EARLY scoped_inst:mux/ALU_intan/c_addsub_1} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/sources_1/bd/ALU/ip/ALU_mult_gen_0_0/ALU_mult_gen_0_0/ALU_mult_gen_0_0_in_context.xdc rfile:../../../../../HW4.srcs/sources_1/bd/ALU/ip/ALU_mult_gen_0_0/ALU_mult_gen_0_0/ALU_mult_gen_0_0_in_context.xdc id:3 order:EARLY scoped_inst:mux/ALU_intan/mult_gen_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/sources_1/bd/ALU/ip/ALU_and16_0_0/ALU_and16_0_0/ALU_and16_0_0_in_context.xdc rfile:../../../../../HW4.srcs/sources_1/bd/ALU/ip/ALU_and16_0_0/ALU_and16_0_0/ALU_and16_0_0_in_context.xdc id:4 order:EARLY scoped_inst:mux/ALU_intan/and16_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/sources_1/bd/ALU/ip/ALU_or16_0_0/ALU_or16_0_0/ALU_or16_0_0_in_context.xdc rfile:../../../../../HW4.srcs/sources_1/bd/ALU/ip/ALU_or16_0_0/ALU_or16_0_0/ALU_or16_0_0_in_context.xdc id:5 order:EARLY scoped_inst:mux/ALU_intan/or16_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/sources_1/bd/ALU/ip/ALU_xor16_0_0/ALU_xor16_0_0/ALU_xor16_0_0_in_context.xdc rfile:../../../../../HW4.srcs/sources_1/bd/ALU/ip/ALU_xor16_0_0/ALU_xor16_0_0/ALU_xor16_0_0_in_context.xdc id:6 order:EARLY scoped_inst:mux/ALU_intan/xor16_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/sources_1/bd/ALU/ip/ALU_div_gen_0_2/ALU_div_gen_0_2/ALU_div_gen_0_2_in_context.xdc rfile:../../../../../HW4.srcs/sources_1/bd/ALU/ip/ALU_div_gen_0_2/ALU_div_gen_0_2/ALU_div_gen_0_2_in_context.xdc id:7 order:EARLY scoped_inst:mux/ALU_intan/div_gen_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/sources_1/bd/ALU/ip/ALU_mod16_0_0/ALU_mod16_0_0/ALU_mod16_0_0_in_context.xdc rfile:../../../../../HW4.srcs/sources_1/bd/ALU/ip/ALU_mod16_0_0/ALU_mod16_0_0/ALU_mod16_0_0_in_context.xdc id:8 order:EARLY scoped_inst:mux/ALU_intan/mod16_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.srcs/constrs_1/imports/Downloads/timing.xdc rfile:../../../../../HW4.srcs/constrs_1/imports/Downloads/timing.xdc id:9} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/nehmy/OneDrive/Desktop/HW4_Blake_Wishard/HW4.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:10} [current_design]
current_instance mux/ALU_intan/c_addsub_0
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance CLK]
current_instance
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mux/ALU_intan/c_addsub_0]
current_instance mux/ALU_intan/c_addsub_1
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance CLK]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mux/ALU_intan/c_addsub_1]
current_instance mux/ALU_intan/mult_gen_0
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance CLK]
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mux/ALU_intan/mult_gen_0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mux/ALU_intan/and16_0]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mux/ALU_intan/or16_0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mux/ALU_intan/xor16_0]
current_instance mux/ALU_intan/div_gen_0
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance aclk]
current_instance
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mux/ALU_intan/div_gen_0]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mux/ALU_intan/mod16_0]
set_property src_info {type:XDC file:9 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan/c_addsub_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan/c_addsub_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan/mult_gen_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan/and16_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan/or16_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan/xor16_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan/div_gen_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mux/ALU_intan/mod16_0]
